### ISSUE TITLE
Can the WordPress wp_create_nonce function be used to generate the session id?

### ISSUE THREAD

**Issue by timnolte** [ndigitals/wp-sqrl#1]
It is ideal if we can utilize built-in WordPress functionality as much as possible. Since WordPress already has a method for creating a nonce, typically used in form submissions, we need to determine if this nonce is a good enough session id. Typically the wp_create_nonce function takes into account the already logged in user however it does facilitate generating a nonce if there is no user logged in. It also provides a hook that can be used to customize the uid during  the logged out state. May be able to use this hook to provide a better starting point for the hash that generates the nonce.

**Comment by deltafactory** [comment]
While I don't enough about SQRL's use of the nonce, I see some possible issues based on WordPress' not-quite-standard use of the "nonce" concept:
1. A given WP nonce has a lifetime of 12 hours given the same combination of arguments of which current time is one. If the user ID is 0 (which is safe to assume, given we're authenticating) then multiple visitors would be given the same nonce if the action parameter is static. This is not one-time use.
2. The length of the nonce (10 characters) may not be long enough.

There are underlying functions that would still be helpful, notably wp_salt() and wp_hash().

I wonder if the following would work:

``` php
function sqrl_nonce() {
    $rand = time() . mt_rand();
    return wp_salt( $rand, 'nonce' );
}
```

**Comment by trianglman** [comment]
That code should work. I've also been working on a generic PHP library that can handle generating the nonces over at https://github.com/trianglman/sqrl. This would handle creating the nonce and QR code but it would need to be wrapped into a Wordpress plugin; something I have little skill at.

I'm still working on getting validation to work; the ed25519 library that you can install on PHP only handles encrypt and decrypt, not signing.

**Comment by aaroneiche** [comment]
I think having the underlying library would be highly beneficial, however care would need to be taken that it was siloed enough that it could be easily upgraded.

**Comment by timnolte** [comment]
@deltafactory good catch on the WP nonce length, I'm not sure I like that restriction either. I was aware of the issue of the 12 hour nonce lifetime but was considering using the nonce_user_logged_out filter which essentially generates a uid which we could supply our once very unique time-based value and the result would be unique nonces for every call potentially. There is actually another filter hook, nonce_life, which would allow us to adjust the lifetime on the nonce but at first glance I think this would result in a global nonce change and would most likely cause a lot of problems with form submissions.

@trianglman I'm actually following your work as well as I would prefer to reuse your library so as to establish some sort of standard, at least for PHP. I'm hopefully that your work will help to overcome the requirement of the Apache libsodium requirement.

**Comment by timnolte** [comment]
@aaroneiche for sure that would be high on my list of requirements for this plugin.

**Comment by trianglman** [comment]
@aaroneiche I'm trying to make the code pretty easy to extend and document where to make changes if you want to improve it.

@timnolte The libsodium thing is quite a climb right now. I have code up that starts to port the python library, but I'm running into bugs where python does math "differently." Like where -5%4 = 3...

**Comment by joshbetz** [comment]
@timnolte I think others have already said this, but the WordPress nonce isn't a real nonce, so it probably shouldn't be used for this.

**Comment by timnolte** [comment]
It looks like the PHP SQRL library will be providing this functionality so that is what will be used.
