### ISSUE TITLE
I can't see qr code login option and can't login with my account password

### ISSUE THREAD

**Issue by niauwu** [ndigitals/wp-sqrl#5]
I can't see qr code login option and can't login with my account password after install the plugin
My wordpress version is 4.0.1.

**Comment by timnolte** [comment]
Apologies, the plugin has no login functionality as of yet. There is currently an Apache module requirement for the PHP SQRL library, which is not common to most shared hosting environments, which puts a bit of a damper on the widespread use of a WordPress plugin. The question of whether a WordPress plugin is actually viable is still in question.
